name: 🚀 Deploy to AWS App Runner

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt  # Adjust if you have a different requirements file
          # The above line was removed as project dependencies are installed during the Docker build process.

      - name: Build Docker image
        run: |
          docker build -t mem0-mcp-server .

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker tag mem0-mcp-server:latest 416431505685.dkr.ecr.us-east-1.amazonaws.com/mem0-mcp-server:latest
          docker push <your_account_id>.dkr.ecr.<region>.amazonaws.com/mem0-mcp-server:latest

      - name: Deploy to AWS App Runner
        run: |
          aws apprunner update-service --service-arn arn:aws:apprunner:us-east-1:416431505685:service/mem0-mcp-app-runner-service/76a8a91661cb4785aaf223ca62cc9434 --source-configuration '{"imageRepository":{"imageIdentifier":"416431505685.dkr.ecr.us-east-1.amazonaws.com/mem0-mcp-server:latest","imageRepositoryType":"ECR"}}'